#!/bin/bash

# Set variables
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Generate the RSA private key
openssl genpkey -algorithm RSA -out $KEY_NAME -aes256 -pass pass:$PASSPHRASE -pkeyopt rsa_keygen_bits:$BITS

# Display message
if [ $? -eq 0 ]; then
    echo "RSA key pair generated successfully!"
    echo "Private key: $KEY_NAME"
else
    echo "Failed to generate RSA key pair."
fi
