#!/usr/bin/env bash

# Variables
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Remove existing key if it exists
rm -f $KEY_NAME $KEY_NAME.pub

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE -q

# Check if key was created successfully
if [ -f "$KEY_NAME" ]; then
    echo "RSA key pair created successfully!"
else
    echo "Failed to create RSA key pair."
    exit 1
fi
