#!/usr/bin/env bash
# Install nginx webserver on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html/index/
echo "Holberton School" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx start
